// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDOrder     int32     `gorm:"column:id_order;not null" json:"id_order"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Photo       string    `gorm:"column:photo" json:"photo"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:current_timestamp()" json:"updated_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
