// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Phone     string    `gorm:"column:phone" json:"phone"`
	Address   string    `gorm:"column:address" json:"address"`
	CreatedAt time.Time `gorm:"column:created_at;default:current_timestamp()" json:"created_at"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
