// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDUser          int32     `gorm:"column:id_user" json:"id_user"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	Message         string    `gorm:"column:message" json:"message"`
	Weight          float32   `gorm:"column:weight;not null" json:"weight"`
	EstimatedTime   time.Time `gorm:"column:estimated_time" json:"estimated_time"`
	Rating          int32     `gorm:"column:rating" json:"rating"`
	StatusConfirmed string    `gorm:"column:status_confirmed" json:"status_confirmed"`
	IsCompleted     string    `gorm:"column:is_completed" json:"is_completed"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:current_timestamp()" json:"updated_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
