// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderDetail = "order_details"

// OrderDetail mapped from table <order_details>
type OrderDetail struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDOrder     int32     `gorm:"column:id_order;not null" json:"id_order"`
	IDTasks     int32     `gorm:"column:id_tasks;not null" json:"id_tasks"`
	IDUser      int32     `gorm:"column:id_user;not null" json:"id_user"`
	IsCompleted string    `gorm:"column:is_completed;not null" json:"is_completed"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:current_timestamp()" json:"updated_at"`
}

// TableName OrderDetail's table name
func (*OrderDetail) TableName() string {
	return TableNameOrderDetail
}
