// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderItemTask = "order_item_tasks"

// OrderItemTask mapped from table <order_item_tasks>
type OrderItemTask struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderItemID int32     `gorm:"column:order_item_id;not null" json:"order_item_id"`
	TaskID      int32     `gorm:"column:task_id;not null" json:"task_id"`
	Price       int32     `gorm:"column:price;not null" json:"price"`
	CreatedAt   time.Time `gorm:"column:created_at;default:current_timestamp()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:current_timestamp()" json:"updated_at"`
}

// TableName OrderItemTask's table name
func (*OrderItemTask) TableName() string {
	return TableNameOrderItemTask
}
