// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskList = "task_lists"

// TaskList mapped from table <task_lists>
type TaskList struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Price       int32     `gorm:"column:price;not null" json:"price"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:current_timestamp()" json:"updated_at"`
}

// TableName TaskList's table name
func (*TaskList) TableName() string {
	return TableNameTaskList
}
