// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Email     string    `gorm:"column:email" json:"email"`
	Password  string    `gorm:"column:password" json:"password"`
	Phone     string    `gorm:"column:phone;not null" json:"phone"`
	Address   string    `gorm:"column:address;not null" json:"address"`
	Role      string    `gorm:"column:role;default:customer" json:"role"`
	CreatedAt time.Time `gorm:"column:created_at;default:current_timestamp()" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
